[package]
name = "mdns"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"  # To interact with C library

[build-dependencies]
cc = "1.0"  # To compile C code
bindgen = "0.63.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
