name: Basic Rust CI pipeline (build+run+test)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build & Run & Test
    - run: |
           cd rust/procure2pay
           ./run_tests.sh
